FixingUserRoles
DShcharbakou/BE-Oct2021-Exadel-Internship-JS-.NET-BA pull request #49
Opened 2021-11-05 10:34 UTC by CatholicCardinal

-create enum UserRoles
-fixing SeedExtention
-move UserRoles adn SeedExtention to Bll layer
-rename TokenService to AuthenticationService
-delete register
-delete unused models UI

2021-11-05 11:32 UTC, VasiliNesterenko commented on BLL/SeedExtension.cs
> +            UserRoles[] roleNames = { UserRoles.admin, UserRoles.recruiter, UserRoles.manager, UserRoles.interviewer, UserRoles.mentor, UserRoles.supermentor };
Please use enumeration of ENUM object

2021-11-05 11:33 UTC, VasiliNesterenko commented on UI/Attribute/OptionalAuthorizeAttribute.cs
>      public class BlacklistAuthorizeAttribute : AuthorizeAttribute, IAuthorizationFilter
Please correct filename: OptionalAuthorizeAttribute.cs  vs BlacklistAuthorizeAttribute

2021-11-05 11:34 UTC, VasiliNesterenko requested changes
Please review my comments

2021-11-05 14:49 UTC, DShcharbakou approved these changes

2021-11-05 14:49 UTC, DShcharbakou commented on UI/Attribute/BlacklistAuthorizeAttribute.cs
> +namespace UI.Attribute
.Attribute**s**

2021-11-05 14:49 UTC, DShcharbakou commented on UI/Controllers/HomeController.cs
> +        UserRoles claim = UserRoles.admin;
For which purpose did you set up this one line?

2021-11-05 14:49 UTC, DShcharbakou commented on UI/Controllers/HomeController.cs
> +        [Authorize()]
If you need using role use enum as a parameter for this attribute

2021-11-05 14:50 UTC, DShcharbakou reviewed
See comments above

2021-11-05 14:51 UTC, DShcharbakou requested changes
See comments above

2021-11-05 15:28 UTC, VasiliNesterenko approved these changes

2021-11-06 20:46 UTC, AnnKirienko approved these changes

2021-11-07 18:52 UTC, DShcharbakou approved these changes

2021-11-07 21:47 UTC, merged