Candidate Service
DShcharbakou/BE-Oct2021-Exadel-Internship-JS-.NET-BA pull request #57
Opened 2021-11-11 14:20 UTC by ArslanTem

2021-11-11 18:39 UTC, DShcharbakou requested changes
Also you need update CandidateDto with necessary fields and CandidateService

2021-11-11 18:39 UTC, DShcharbakou commented on DAL/InternshipDbContext.cs
> +
???

2021-11-11 18:39 UTC, DShcharbakou commented on DAL/Repositories/CandidateRepository.cs
> +        public CandidateSet(InternshipDbContext internshipDbContext) : base(internshipDbContext) { }
What is it?

2021-11-11 18:39 UTC, DShcharbakou commented on DAL/Repositories/UnitOfWork.cs
> +                    this.candidateRep = new CandidateSet(internshipDbContext);
for what purpose did you rename it?

2021-11-11 18:39 UTC, DShcharbakou commented on UI/Controllers/CandidatesController.cs
> +        private ICandidateService candidateService;
private readonly

2021-11-11 18:39 UTC, DShcharbakou commented on UI/Controllers/CandidatesController.cs
> +        private ICandidateService candidateService;
where is the constructor with service injection? Do you test this code? This code doesn't work!

2021-11-11 18:39 UTC, DShcharbakou commented on UI/Controllers/CandidatesController.cs
> +        }
for what purposes do you need these methods?

2021-11-11 18:39 UTC, DShcharbakou commented on UI/Controllers/CandidatesController.cs
> +        }
for what purposes do you need this method?

2021-11-11 18:39 UTC, DShcharbakou commented on UI/Controllers/CandidatesController.cs
> +        public void Save(int id, [FromBody] CandidateDTO candidate)
via this method you will register candidate to the sandbox. Why this method call "Save"?

2021-11-11 18:39 UTC, DShcharbakou commented on UI/Controllers/CandidatesController.cs
> +        [HttpPost("{id}")]
I suppose it should be sandboxId

2021-11-11 18:39 UTC, DShcharbakou commented on UI/Controllers/CandidatesController.cs
> +            candidateService.AddCandidate(candidate);
where is second parameter for sandboxId? rename this method, for example candidateService.RegisterCandidate(id, candidateDto)

2021-11-14 15:51 UTC, ArslanTem commented on DAL/InternshipDbContext.cs
> +
ctrl+k+d

2021-12-07 07:11 UTC, closed without merging