Adding Specifications
DShcharbakou/BE-Oct2021-Exadel-Internship-JS-.NET-BA pull request #58
Opened 2021-11-12 14:39 UTC by wollentimer

2021-11-12 21:33 UTC, DShcharbakou reviewed
There are a lot of unnecessary things. It needs to rewrite.

2021-11-16 15:10 UTC, VasiliNesterenko approved these changes

2021-11-16 15:14 UTC, VasiliNesterenko commented on DAL/Repositories/UnitOfWork.cs
> -        private IBaseRepository<Country> countryRep;
please, do not move/exchange rows which are not related to your changes
in this case there can be merge conflicts
please review UnitOfWork.cs in the MAIN repo and make appropriate changes

2021-11-16 15:14 UTC, VasiliNesterenko requested changes
please find my comment for UnitOfWork

2021-11-17 06:27 UTC, VasiliNesterenko approved these changes

2021-11-17 07:32 UTC, AnnKirienko approved these changes

2021-11-17 11:54 UTC, Alexy-Def approved these changes

2021-11-17 12:08 UTC, merged