UI layer nk(new endpoints)
DShcharbakou/BE-Oct2021-Exadel-Internship-JS-.NET-BA pull request #78
Opened 2021-11-30 21:30 UTC by wollentimer

2021-11-30 23:41 UTC, AnnKirienko approved these changes

2021-12-01 06:23 UTC, Alexy-Def approved these changes

2021-12-01 07:24 UTC, DShcharbakou requested changes

2021-12-01 07:24 UTC, DShcharbakou commented on BLL/Interfaces/ISkillService.cs
> +        IEnumerable<SkillDTO> GetListSkillDTO();
GetListSkill2DTO vs GetListSkillDTO. I don't know about differences between these models. I suggest renamed them.

2021-12-01 10:26 UTC, AnnKirienko approved these changes

2021-12-01 15:28 UTC, CatholicCardinal approved these changes

2021-12-01 15:29 UTC, merged